
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
    service: kafka-consumer
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: kafka-consumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
      version: v1
  template:
    metadata:
      labels:
        app: kafka-consumer
        version: v1
    spec:
      containers:
      - name: kafka-consumer
        image: docker.io/library/kafka-consumer:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
---
